---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
    annotations:
        github.com/project-slug: Humanitec-DemoOrg/onlineboutique-demo
    description: online-boutique
    links:
        - icon: github
          title: Repository
          url: https://github.com/Humanitec-DemoOrg/onlineboutique-demo
    name: online-boutique
spec:
    owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    annotations:
        github.com/project-slug: Humanitec-DemoOrg/onlineboutique-demo
    description: ad
    links:
        - icon: github
          title: Repository
          url: https://github.com/Humanitec-DemoOrg/onlineboutique-demo
    name: online-boutique-ad
    title: ad
spec:
    lifecycle: experimental
    owner: user:guest
    system: online-boutique
    type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    annotations:
        github.com/project-slug: Humanitec-DemoOrg/onlineboutique-demo
    description: cart
    links:
        - icon: github
          title: Repository
          url: https://github.com/Humanitec-DemoOrg/onlineboutique-demo
    name: online-boutique-cart
    title: cart
spec:
    dependsOn:
        - resource:online-boutique-cart-redis-cart
    lifecycle: experimental
    owner: user:guest
    system: online-boutique
    type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    annotations:
        github.com/project-slug: Humanitec-DemoOrg/onlineboutique-demo
    description: checkout
    links:
        - icon: github
          title: Repository
          url: https://github.com/Humanitec-DemoOrg/onlineboutique-demo
    name: online-boutique-checkout
    title: checkout
spec:
    dependsOn:
        - component:online-boutique-cart
        - component:online-boutique-currency
        - component:online-boutique-email
        - component:online-boutique-payment
        - component:online-boutique-productcatalog
        - component:online-boutique-shipping
    lifecycle: experimental
    owner: user:guest
    system: online-boutique
    type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    annotations:
        github.com/project-slug: Humanitec-DemoOrg/onlineboutique-demo
    description: currency
    links:
        - icon: github
          title: Repository
          url: https://github.com/Humanitec-DemoOrg/onlineboutique-demo
    name: online-boutique-currency
    title: currency
spec:
    lifecycle: experimental
    owner: user:guest
    system: online-boutique
    type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    annotations:
        github.com/project-slug: Humanitec-DemoOrg/onlineboutique-demo
    description: email
    links:
        - icon: github
          title: Repository
          url: https://github.com/Humanitec-DemoOrg/onlineboutique-demo
    name: online-boutique-email
    title: email
spec:
    lifecycle: experimental
    owner: user:guest
    system: online-boutique
    type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    annotations:
        github.com/project-slug: Humanitec-DemoOrg/onlineboutique-demo
    description: frontend
    links:
        - icon: github
          title: Repository
          url: https://github.com/Humanitec-DemoOrg/onlineboutique-demo
    name: online-boutique-frontend
    title: frontend
spec:
    dependsOn:
        - component:online-boutique-ad
        - component:online-boutique-cart
        - component:online-boutique-checkout
        - component:online-boutique-currency
        - resource:online-boutique-frontend-dns
        - component:online-boutique-payment
        - component:online-boutique-productcatalog
        - component:online-boutique-recommendation
        - component:online-boutique-shipping
    lifecycle: experimental
    owner: user:guest
    system: online-boutique
    type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    annotations:
        github.com/project-slug: Humanitec-DemoOrg/onlineboutique-demo
    description: loadgenerator
    links:
        - icon: github
          title: Repository
          url: https://github.com/Humanitec-DemoOrg/onlineboutique-demo
    name: online-boutique-loadgenerator
    title: loadgenerator
spec:
    dependsOn:
        - component:online-boutique-frontend
    lifecycle: experimental
    owner: user:guest
    system: online-boutique
    type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    annotations:
        github.com/project-slug: Humanitec-DemoOrg/onlineboutique-demo
    description: payment
    links:
        - icon: github
          title: Repository
          url: https://github.com/Humanitec-DemoOrg/onlineboutique-demo
    name: online-boutique-payment
    title: payment
spec:
    lifecycle: experimental
    owner: user:guest
    system: online-boutique
    type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    annotations:
        github.com/project-slug: Humanitec-DemoOrg/onlineboutique-demo
    description: productcatalog
    links:
        - icon: github
          title: Repository
          url: https://github.com/Humanitec-DemoOrg/onlineboutique-demo
    name: online-boutique-productcatalog
    title: productcatalog
spec:
    lifecycle: experimental
    owner: user:guest
    system: online-boutique
    type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    annotations:
        github.com/project-slug: Humanitec-DemoOrg/onlineboutique-demo
    description: recommendation
    links:
        - icon: github
          title: Repository
          url: https://github.com/Humanitec-DemoOrg/onlineboutique-demo
    name: online-boutique-recommendation
    title: recommendation
spec:
    dependsOn:
        - component:online-boutique-productcatalog
    lifecycle: experimental
    owner: user:guest
    system: online-boutique
    type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    annotations:
        github.com/project-slug: Humanitec-DemoOrg/onlineboutique-demo
    description: shipping
    links:
        - icon: github
          title: Repository
          url: https://github.com/Humanitec-DemoOrg/onlineboutique-demo
    name: online-boutique-shipping
    title: shipping
spec:
    lifecycle: experimental
    owner: user:guest
    system: online-boutique
    type: service
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
    description: online-boutique-cart-redis-cart
    name: online-boutique-cart-redis-cart
    title: redis-cart
spec:
    owner: user:guest
    system: online-boutique
    type: redis
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
    description: online-boutique-frontend-dns
    name: online-boutique-frontend-dns
    title: dns
spec:
    owner: user:guest
    system: online-boutique
    type: dns
