apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cart
  description: Cart Service for Online Boutique
  tags:
    - dotnet
    - backend
    - grpc
  links:
    - url: https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/src/cartservice
      title: Source code
      icon: help
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  system: online-boutique
  apiConsumedBy: ['component:frontend', 'component:checkoutservice']
  dependsOn: ['resource:redis-cart']
