apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cart
  description: Cart Service
  annotations:
    github.com/project-slug: Humanitec-DemoOrg/onlineboutique-demo
  tags:
    - dotnet
    - backend
    - grpc
  links:
    - url: https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/src/cartservice
      title: Source code
      icon: help
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  system: online-boutique
  apiConsumedBy: ['component:frontend', 'component:checkoutservice']
  dependsOn: ['resource:redis-cart']
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: redis-cart
  description: Redis database
spec:
  type: database
  owner: user:guest
  system: online-boutique