apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: checkout
  description: Checkout service
  annotations:
    github.com/project-slug: Humanitec-DemoOrg/onlineboutique-demo
  tags:
    - golang
    - backend
    - grpc
  links:
    - url: https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/src/frontend
      title: Source code
      icon: help
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  system: online-boutique
  apiConsumedBy: ['component:frontend']
  dependsOn:
  - 'component:cart'
  - 'component:currency'
  - 'component:payment'
  - 'component:email'
  - 'component:productcatalog'