name: close-pr
on:
  pull_request:
    types:
      - closed
env:
  ENVIRONMENT_ID: pr-${{ github.event.number }}
  HUMCTL_VERSION: '0.23.1'
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout humctl bin
        uses: actions/checkout@v3
      - name: install humctl
        uses: humanitec/setup-cli-action@v1
        with:
          version: ${{ env.HUMCTL_VERSION }}
      - name: delete humanitec env
        run: |
          humctl delete env ${{ env.ENVIRONMENT_ID }} \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --org ${{ secrets.HUMANITEC_ORG }} \
              --app ${{ vars.APP_NAME }}