name: frontend-close-pr
on:
  pull_request:
    paths:
      - 'apps/frontend/**'
      - '.github/workflows/frontend-close-pr.yaml'
    types:
      - closed
env:
  ENVIRONMENT_ID: pr-${{ github.event.number }}-frontend
  HUMCTL_VERSION: '0.12.0'
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout humctl bin
        uses: actions/checkout@v3
      - name: install humctl
        run: |
          curl -fLO https://storage.googleapis.com/humctl-releases/v${{ env.HUMCTL_VERSION }}/cli_${{ env.HUMCTL_VERSION }}_linux_amd64.tar.gz
          tar xvzf cli_${{ env.HUMCTL_VERSION }}_linux_amd64.tar.gz
          rm cli_${{ env.HUMCTL_VERSION }}_linux_amd64.tar.gz README.md
          chmod +x humctl
          mv humctl /usr/local/bin
      - name: delete humanitec env
        run: |
          humctl delete env ${{ env.ENVIRONMENT_ID }} \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --org ${{ secrets.HUMANITEC_ORG }} \
              --app ${{ vars.APP_NAME }}